version: '3.9'  # Use a compatible version

services:
  django:
    build: .
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8000:8000"  # Expose Django app on port 8000
    environment:
      - DEBUG=True  # Enable Django Debug mode
      - PYTHONUNBUFFERED=1  # Prevent Python from buffering stdout/stderr

# Note: No database service needed for SQLite, as it uses a file-based database.