# Generated by Django 5.1.2 on 2024-10-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seasonalevents'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('IS', 'In Stock'), ('OOS', 'Out of sotck'), ('BO', 'Back Ordered')], default='OOS', max_length=3),
        ),
        migrations.AddField(
            model_name='productline',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='productline',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonalevents',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seasonalevents',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
