# Generated by Django 5.0.7 on 2024-08-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0002_テナント_レポート日_保証会社_物件_管理項目_請求先_ステータス_契約_敷金保証金_売上_費用'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ステータス',
            name='レポート日',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='費用',
            name='レポート日',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='売上',
            name='レポート日',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='レポート日',
        ),
    ]
