# Generated by Django 5.0.7 on 2024-08-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0003_alter_ステータス_レポート日_alter_費用_レポート日_alter_売上_レポート日_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthSelect',
            fields=[
                ('MonthSelect', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
