# Generated by Django 5.0.7 on 2024-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0006_alter_テナント_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ステータス',
            name='その他',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='テナント関連',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='メンテナンス',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='新テナント',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='検査情報',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='特別項目',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ステータス',
            name='遅延状況',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='売上',
            name='備考',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='契約',
            name='フリーレント',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='契約',
            name='保証有無',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='契約',
            name='備考',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='契約',
            name='現在契約終了日',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='契約',
            name='現在契約開始日',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='敷金保証金',
            name='当月増額',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='敷金保証金',
            name='当月減少',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='敷金保証金',
            name='移動予定日',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='費用',
            name='備考',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
