# Generated by Django 5.0.7 on 2024-08-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0007_alter_ステータス_その他_alter_ステータス_テナント関連_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='売上',
            name='請求消費税',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='売上',
            name='請求金額',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
