# Generated by Django 5.0.7 on 2024-08-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0008_alter_売上_請求消費税_alter_売上_請求金額'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='契約',
            name='保証会社名',
        ),
        migrations.AddField(
            model_name='契約',
            name='保証会社コード',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='solitonRE.保証会社'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='契約',
            name='フリーレント',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
