# Generated by Django 5.0.7 on 2024-08-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0009_remove_契約_保証会社名_契約_保証会社コード_alter_契約_フリーレント'),
    ]

    operations = [
        migrations.RenameField(
            model_name='契約',
            old_name='契約番号',
            new_name='契約ID',
        ),
    ]
