# Generated by Django 5.0.7 on 2024-08-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0010_rename_契約番号_契約_契約id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='売上',
            old_name='請求書発行月',
            new_name='請求書発行日',
        ),
    ]
