# Generated by Django 5.0.7 on 2024-08-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0011_rename_請求書発行月_売上_請求書発行日'),
    ]

    operations = [
        migrations.RenameField(
            model_name='売上',
            old_name='請求税金込',
            new_name='請求税込金額',
        ),
    ]
