# Generated by Django 5.0.7 on 2024-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0012_rename_請求税金込_売上_請求税込金額'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='売上',
            name='当月入金額',
        ),
        migrations.AddField(
            model_name='売上',
            name='当月入金日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
