# Generated by Django 5.0.7 on 2024-08-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0013_remove_売上_当月入金額_売上_当月入金日'),
    ]

    operations = [
        migrations.AlterField(
            model_name='売上',
            name='計上日',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='売上',
            name='請求税込金額',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
