# Generated by Django 5.0.7 on 2024-08-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0014_alter_売上_計上日_alter_売上_請求税込金額'),
    ]

    operations = [
        migrations.AlterField(
            model_name='費用',
            name='当月支払日',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='費用',
            name='請求消費税',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='費用',
            name='請求税込金',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='費用',
            name='請求金額',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
