# Generated by Django 5.0.7 on 2024-08-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0015_alter_費用_当月支払日_alter_費用_請求消費税_alter_費用_請求税込金_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='費用',
            old_name='請求税込金',
            new_name='請求税金込',
        ),
    ]
