# Generated by Django 5.0.7 on 2024-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0018_alter_monthselect_monthselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('請求金額', models.IntegerField(blank=True, null=True)),
                ('請求消費税', models.IntegerField(blank=True, null=True)),
                ('請求税込金額', models.IntegerField(blank=True, null=True)),
                ('テナントID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.テナント')),
                ('物件ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件')),
                ('管理項目コード', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.管理項目')),
            ],
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('レポート日', models.DateField()),
                ('該当月開始月', models.DateField()),
                ('該当月終了月', models.DateField()),
                ('請求書発行日', models.DateField()),
                ('入金予定日', models.DateField()),
                ('計上日', models.DateField(blank=True, null=True)),
                ('請求金額', models.IntegerField(blank=True, null=True)),
                ('請求消費税', models.IntegerField(blank=True, null=True)),
                ('請求税込金額', models.IntegerField(blank=True, null=True)),
                ('当月入金日', models.DateField(blank=True, null=True)),
                ('備考', models.CharField(blank=True, max_length=200, null=True)),
                ('DeleteFlag', models.BooleanField(default=False)),
                ('テナントID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.テナント')),
                ('物件ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件')),
                ('管理項目コード', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.管理項目')),
            ],
        ),
    ]
