# Generated by Django 5.0.7 on 2024-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0019_defaultinput_inputfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfield',
            name='DeleteFlag',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='レポート日',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='備考',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='入金予定日',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='当月入金日',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='計上日',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='該当月終了月',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='該当月開始月',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='請求書発行日',
        ),
    ]
