# Generated by Django 5.0.7 on 2024-08-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0020_remove_inputfield_deleteflag_remove_inputfield_レポート日_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultInput',
        ),
    ]
