# Generated by Django 5.0.7 on 2024-08-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0022_契約_部屋番号'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfield',
            name='請求消費税',
        ),
        migrations.RemoveField(
            model_name='inputfield',
            name='請求税込金額',
        ),
        migrations.AddField(
            model_name='inputfield',
            name='契約ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solitonRE.契約'),
        ),
    ]
