# Generated by Django 5.0.7 on 2024-08-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0023_remove_inputfield_請求消費税_remove_inputfield_請求税込金額_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='売上',
            old_name='契約番号',
            new_name='契約ID',
        ),
    ]
