# Generated by Django 5.0.7 on 2024-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0024_rename_契約番号_売上_契約id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='売上',
            name='入金予定日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
