# Generated by Django 5.0.7 on 2024-08-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0025_alter_売上_入金予定日'),
    ]

    operations = [
        migrations.AddField(
            model_name='テナント',
            name='テナント短縮名',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
