# Generated by Django 5.0.7 on 2024-08-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0028_alter_monthselect_monthselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='敷金保証金',
            name='物件ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件'),
            preserve_default=False,
        ),
    ]
