# Generated by Django 5.0.7 on 2024-08-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0029_敷金保証金_物件id'),
    ]

    operations = [
        migrations.AddField(
            model_name='敷金保証金',
            name='備考',
            field=models.DateField(blank=True, null=True),
        ),
    ]
