# Generated by Django 5.0.7 on 2024-08-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0030_敷金保証金_備考'),
    ]

    operations = [
        migrations.AddField(
            model_name='ステータス',
            name='物件ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件'),
            preserve_default=False,
        ),
    ]
