# Generated by Django 5.0.7 on 2024-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0031_ステータス_物件id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='費用',
            name='計上日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
