# Generated by Django 5.0.7 on 2024-08-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0032_alter_費用_計上日'),
    ]

    operations = [
        migrations.AddField(
            model_name='テナント',
            name='テナントソート',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
