# Generated by Django 5.0.7 on 2024-08-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0033_テナント_テナントソート'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BM項目', models.CharField(max_length=30)),
                ('BM回数', models.CharField(max_length=30)),
                ('BM予定数', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BMInputFiled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('物件ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件')),
                ('BM項目', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.bmitems')),
            ],
        ),
        migrations.CreateModel(
            name='BM入力フォーム',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('レポート日', models.DateField()),
                ('BM予定', models.CharField(max_length=30)),
                ('BM実施', models.CharField(max_length=30)),
                ('BMコメント', models.CharField(max_length=255)),
                ('BM項目', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.bmitems')),
                ('物件ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitonRE.物件')),
            ],
        ),
    ]
