# Generated by Django 5.0.7 on 2024-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0034_bmitems_bminputfiled_bm入力フォーム'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BMInputFiled',
            new_name='BMInputField',
        ),
        migrations.AddField(
            model_name='bmitems',
            name='BM項目CD',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
