# Generated by Django 5.0.7 on 2024-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0035_rename_bminputfiled_bminputfield_bmitems_bm項目cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm入力フォーム',
            name='BM予定数',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bm入力フォーム',
            name='BM回数',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
