# Generated by Django 5.0.7 on 2024-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitonRE', '0037_alter_bm入力フォーム_bmコメント_alter_bm入力フォーム_bm予定_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmitems',
            name='BM予定数',
        ),
        migrations.RemoveField(
            model_name='bmitems',
            name='BM回数',
        ),
        migrations.AddField(
            model_name='bminputfield',
            name='BM予定数',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bminputfield',
            name='BM回数',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmitems',
            name='BM内容説明',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
