# Generated by Django 5.0.7 on 2024-09-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solitonRE', '0037_alter_bm入力フォーム_bmコメント_alter_bm入力フォーム_bm予定_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('BKID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('BK名', models.CharField(max_length=100)),
                ('BK担当者名', models.CharField(max_length=20)),
                ('BKEメール', models.CharField(max_length=30)),
                ('BK電話番号', models.CharField(max_length=20)),
                ('BK住所', models.CharField(max_length=100)),
                ('BK短名', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RP日付', models.DateField()),
                ('RP内容', models.CharField(max_length=255)),
                ('BKID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('物件ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solitonRE.物件')),
            ],
        ),
    ]
