# Generated by Django 5.0.7 on 2024-09-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_broker_bkeメール'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='BK会社番号',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='BK住所',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='BK短名',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='BK電話番号',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
